IMITM	NUMERIC	8	 	YES
IMLITM	VARCHAR			YES
IMAITM	VARCHAR			YES
IMDSC1	VARCHAR			YES
IMDSC2	VARCHAR			YES
IMSRTX	VARCHAR			YES
IMALN	VARCHAR			YES
IMSRP1	VARCHAR			YES
IMSRP2	VARCHAR			YES
IMSRP3	VARCHAR			YES
IMSRP4	VARCHAR			YES
IMSRP5	VARCHAR			YES
IMSRP6	VARCHAR			YES
IMSRP7	VARCHAR			YES
IMSRP8	VARCHAR			YES
IMSRP9	VARCHAR			YES
IMSRP0	VARCHAR			YES
IMPRP1	VARCHAR			YES
IMPRP2	VARCHAR			YES
IMPRP3	VARCHAR			YES
IMPRP4	VARCHAR			YES
IMPRP5	VARCHAR			YES
IMPRP6	VARCHAR			YES
IMPRP7	VARCHAR			YES
IMPRP8	VARCHAR			YES
IMPRP9	VARCHAR			YES
IMPRP0	VARCHAR			YES
IMCDCD	VARCHAR			YES
IMPDGR	VARCHAR			YES
IMDSGP	VARCHAR			YES
IMPRGR	VARCHAR			YES
IMRPRC	VARCHAR			YES
IMORPR	VARCHAR			YES
IMBUYR	NUMERIC	8	0	YES
IMDRAW	VARCHAR			YES
IMRVNO	VARCHAR			YES
IMDSZE	CHAR			YES
IMVCUD	NUMERIC	15	4	YES
IMCARS	NUMERIC	8	0	YES
IMCARP	NUMERIC	8	0	YES
IMSHCN	VARCHAR			YES
IMSHCM	VARCHAR			YES
IMUOM1	VARCHAR			YES
IMUOM2	VARCHAR			YES
IMUOM3	VARCHAR			YES
IMUOM4	VARCHAR			YES
IMUOM6	VARCHAR			YES
IMUOM8	VARCHAR			YES
IMUOM9	VARCHAR			YES
IMUWUM	VARCHAR			YES
IMUVM1	VARCHAR			YES
IMSUTM	VARCHAR			YES
IMUMVW	CHAR			YES
IMCYCL	VARCHAR			YES
IMGLPT	VARCHAR			YES
IMPLEV	CHAR			YES
IMPPLV	CHAR			YES
IMCLEV	CHAR			YES
IMPRPO	CHAR			YES
IMCKAV	CHAR			YES
IMBPFG	CHAR			YES
IMSRCE	CHAR			YES
IMOT1Y	CHAR			YES
IMOT2Y	CHAR			YES
IMSTDP	NUMERIC	7	3	YES
IMFRMP	NUMERIC	7	3	YES
IMTHRP	NUMERIC	7	3	YES
IMSTDG	VARCHAR			YES
IMFRGD	VARCHAR			YES
IMTHGD	VARCHAR			YES
IMCOTY	CHAR			YES
IMSTKT	CHAR			YES
IMLNTY	VARCHAR			YES
IMCONT	CHAR			YES
IMBACK	CHAR			YES
IMIFLA	VARCHAR			YES
IMTFLA	VARCHAR			YES
IMINMG	VARCHAR			YES
IMABCS	CHAR			YES
IMABCM	CHAR			YES
IMABCI	CHAR			YES
IMOVR	CHAR			YES
IMWARR	VARCHAR			YES
IMCMCG	VARCHAR			YES
IMSRNR	CHAR			YES
IMPMTH	CHAR			YES
IMFIFO	CHAR			YES
IMLOTS	CHAR			YES
IMSLD	NUMERIC	6	0	YES
IMANPL	NUMERIC	8	 	YES
IMMPST	CHAR			YES
IMPCTM	NUMERIC	7	3	YES
IMMMPC	NUMERIC	7	3	YES
IMPTSC	VARCHAR			YES
IMSNS	CHAR			YES
IMLTLV	NUMERIC	5	0	YES
IMLTMF	NUMERIC	5	0	YES
IMLTCM	NUMERIC	5	0	YES
IMOPC	CHAR			YES
IMOPV	NUMERIC	15	0	YES
IMACQ	NUMERIC	15	2	YES
IMMLQ	NUMERIC	15	2	YES
IMLTPU	NUMERIC	5	2	YES
IMMPSP	CHAR			YES
IMMRPP	CHAR			YES
IMITC	CHAR			YES
IMORDW	CHAR			YES
IMMTF1	NUMERIC	5	0	YES
IMMTF2	NUMERIC	5	0	YES
IMMTF3	NUMERIC	5	0	YES
IMMTF4	NUMERIC	5	0	YES
IMMTF5	NUMERIC	5	0	YES
IMEXPD	NUMERIC	5	0	YES
IMDEFD	NUMERIC	5	0	YES
IMSFLT	NUMERIC	5	0	YES
IMMAKE	CHAR			YES
IMCOBY	CHAR			YES
IMLLX	NUMERIC	3	 	YES
IMCMGL	CHAR			YES
IMCOMH	NUMERIC	3	 	YES
IMURCD	VARCHAR			YES
IMURDT	DATE			YES
IMURAT	NUMERIC	15	2	YES
IMURAB	NUMERIC	8	0	YES
IMURRF	VARCHAR			YES
IMUSER	VARCHAR			YES
IMPID	VARCHAR			YES
IMJOBN	VARCHAR			YES
IMUPMJ	DATE			YES
IMTDAY	NUMERIC	6	 	YES
IMUPCN	VARCHAR			YES
IMSCC0	VARCHAR			YES
IMUMUP	VARCHAR			YES
IMUMDF	VARCHAR			YES
IMUMS0	VARCHAR			YES
IMUMS1	VARCHAR			YES
IMUMS2	VARCHAR			YES
IMUMS3	VARCHAR			YES
IMUMS4	VARCHAR			YES
IMUMS5	VARCHAR			YES
IMUMS6	VARCHAR			YES
IMUMS7	VARCHAR			YES
IMUMS8	VARCHAR			YES
IMPOC	CHAR			YES
IMAVRT	NUMERIC	15	2	YES
IMEQTY	VARCHAR			YES
IMWTRQ	CHAR			YES
IMTMPL	VARCHAR			YES
IMSEG1	VARCHAR			YES
IMSEG2	VARCHAR			YES
IMSEG3	VARCHAR			YES
IMSEG4	VARCHAR			YES
IMSEG5	VARCHAR			YES
IMSEG6	VARCHAR			YES
IMSEG7	VARCHAR			YES
IMSEG8	VARCHAR			YES
IMSEG9	VARCHAR			YES
IMSEG0	VARCHAR			YES
IMMIC	CHAR			YES
IMAING	CHAR			YES
IMBBDD	NUMERIC	6	0	YES
IMCMDM	CHAR			YES
IMLECM	CHAR			YES
IMLEDD	NUMERIC	6	0	YES
IMPEFD	NUMERIC	6	0	YES
IMSBDD	NUMERIC	6	0	YES
IMU1DD	NUMERIC	6	0	YES
IMU2DD	NUMERIC	6	0	YES
IMU3DD	NUMERIC	6	0	YES
IMU4DD	NUMERIC	6	0	YES
IMU5DD	NUMERIC	6	0	YES
IMDLTL	NUMERIC	7	2	YES
IMDPPO	CHAR			YES
IMDUAL	CHAR			YES
IMXDCK	CHAR			YES
IMLAF	CHAR			YES
IMLTFM	CHAR			YES
IMRWLA	CHAR			YES
IMLNPA	CHAR			YES
IMLOTC	VARCHAR			YES
IMAPSC	CHAR			YES
IMAUOM	VARCHAR			YES
IMCONB	CHAR			YES
IMGCMP	CHAR			YES
IMPRI1	NUMERIC	15	4	YES
IMPRI2	NUMERIC	15	4	YES
IMASHL	CHAR			YES
IMVMINV	CHAR			YES
IMCMETH	CHAR			YES
IMEXPI	CHAR			YES